name: pull-request-gate

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build-gate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Testing.Randoms.sln

    - name: Build Testing.Randoms
      run: dotnet build src/Testing.Randoms/Testing.Randoms.csproj -c Release --no-restore -f netstandard2.0
      